<a href="https://colab.research.google.com/github/Asilbek-dev309/python_javoblar/blob/main/Numpy_asoslar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
data=[1,2,4,4.3,34]
arr=np.array(data)

In [ ]:
data

[1, 2, 4, 4.3, 34]

In [ ]:
arr

array([ 1. ,  2. ,  4. ,  4.3, 34. ])

In [ ]:
data0=(5,55,78,3.3,45)
arr0=np.array(data0)

In [ ]:
data0

(5, 55, 78, 3.3, 45)

In [ ]:
arr0

array([ 5. , 55. , 78. ,  3.3, 45. ])

In [ ]:
arr.ndim


1

In [ ]:
arr0.ndim

1

In [ ]:
data1 = [[1,2,3,4.4,4], [12,5,78,89,9],[12.4,4444,444,79,0.1]]
arr1 = np.array(data1)

In [ ]:
data1

[[1, 2, 3, 4.4, 45], [12, 45, 78, 89, 90], [12.4, 4444, 444444, 789, 0.1]]

In [ ]:
arr1

array([[1.00000e+00, 2.00000e+00, 3.00000e+00, 4.40000e+00, 4.50000e+01],
       [1.20000e+01, 4.50000e+01, 7.80000e+01, 8.90000e+01, 9.00000e+01],
       [1.24000e+01, 4.44400e+03, 4.44444e+05, 7.89000e+02, 1.00000e-01]])

In [ ]:
data2=[[22,22,2.2,0.2],[23,4,78,11],[13,56,8,90]]
arr2=np.array(data2)

In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape

(3, 4)

In [ ]:
arr2.size

12

In [ ]:
arr3=np.zeros(shape=(2,5))
arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr4=np.ones((2,7))
arr4

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
arr5=np.arange(23,56,2)
arr5

array([23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55])

In [ ]:
arr6=np.arange(23)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])